version: "3.9"

services:
  db:
    image: postgres:17
    container_name: odoo18_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  odoo:
    build:
      context: ./odoo
      dockerfile: Dockerfile
    container_name: odoo18_app
    depends_on:
      - db
    ports:
      - "${ODOO_PORT}:8069"
    environment:
      HOST: db
      USER: ${POSTGRES_USER}
      PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./odoo/custom_addons:/mnt/extra-addons
      - ./config/odoo.conf:/etc/odoo/odoo.conf

volumes:
  pg_data: